### ISSUE TITLE
Schnittstellen für HyperMode-Seite

### ISSUE THREAD

**Issue by mrothauer** [anstiftung/mapped-repair-events#104]
* [x] JSON für Initiativen
* [x] JSON für Splitter: https://www.reparatur-initiativen.de/files/kcfinder/pages/15203 dateien auslesen, ina bereinigt die dateien, json, SPLiTTER No. 3/2021 auch dazu als name
* [x] offen zugänglich
* [x] Filter: Status = APP_ON

**Comment by inahmmlmnn** [comment]
Für den .json Auszug der Reparatur-Initiativen bräuchten wir bitte:

    - nur Initiativen, die online geschaltet sind
    - Sortierung nach "neuste zuerst"
   - Name der Initiative
   - Ortsname (ohne Adresse, ohne PLZ)
   - Profil-URL
    - Logo (ist eine Unterscheidung nach "eigenes Logo hochgeladen" / "Standardlogo" möglich?)
   - Reparatur-Kategorien, wenn die Benennung wie im Formular lautet (3D-Reparatur, Fahrrad,...)

Wird im iCal-Feed die Termin-URL des jeweiligen Termins mitgeliefert?

**Comment by inahmmlmnn** [comment]
SPLiTTER Ausgaben habe ich alle umbenannt und hochgeladen, ist jetzt einheitlich: https://www.reparatur-initiativen.de/seite/splitter

**Comment by mrothauer** [comment]
> Wird im iCal-Feed die Termin-URL des jeweiligen Termins mitgeliefert?
Ja, ist im Feld "Description" mit drin.

Ich bin fertig - du kannst folgende Links weitergeben:
* https://www.reparatur-initiativen.de/api/splitter (ich gebe auch noch die Dateigröße mit aus)
* https://www.reparatur-initiativen.de/api/workshops
