### ISSUE TITLE
iCal Feed

### ISSUE THREAD

**Issue by inahmmlmnn** [anstiftung/mapped-repair-events#115]
Wurde mir eben am Telefon geschildert: 

Wenn ein Termineintrag auf der Plattform offline geschaltet wird, gibt der zugehörige iCal-Feed keine Termine mehr aus. (Kalender erscheint "leer")

Wird ein zukünftiger Termin als "offline" gespeichert, erscheint er manchmal und manchmal nicht im iCal-Feed

**Comment by mrothauer** [comment]
> Wenn ein Termineintrag auf der Plattform offline geschaltet wird, gibt der zugehörige iCal-Feed keine Termine mehr aus. (Kalender erscheint "leer")

Konnte ich nicht reproduzieren. Kann es sein, dass es der letzte Termineintrag war, der online war?

> Wird ein zukünftiger Termin als "offline" gespeichert, erscheint er manchmal und manchmal nicht im iCal-Feed

Auch das hab ich getestet: Es wurde bei mir immer korrekt nur die Online-Termine anzeigt.

Gibt's noch mehr Infos?

**Comment by inahmmlmnn** [comment]
Ich frage mal nach Betriebssystem, Browser und weiteren Details…

 

Von: Mario Rothauer ***@***.***> 
Gesendet: Dienstag, 28. Februar 2023 15:26
An: anstiftung/mapped-repair-events ***@***.***>
Cc: Ina Hemmelmann ***@***.***>; Author ***@***.***>
Betreff: Re: [anstiftung/mapped-repair-events] iCal Feed (Issue #115)

 

Wenn ein Termineintrag auf der Plattform offline geschaltet wird, gibt der zugehörige iCal-Feed keine Termine mehr aus. (Kalender erscheint "leer")

Konnte ich nicht reproduzieren. Kann es sein, dass es der letzte Termineintrag war, der online war?

Wird ein zukünftiger Termin als "offline" gespeichert, erscheint er manchmal und manchmal nicht im iCal-Feed

Auch das hab ich getestet: Es wurde bei mir immer korrekt nur die Online-Termine anzeigt.

Gibt's noch mehr Infos?

**Comment by mrothauer** [comment]
Und bitte auch, um welche Initiative / welchen Termin es sich gehandelt hat. Danke.

**Comment by inahmmlmnn** [comment]
https://www.reparatur-initiativen.de/repaircafe-hanau 
https://www.reparatur-initiativen.de/repair-cafe-on-tour

Der Anrufer ist hier Organisator.
Lg
Ina

 

Von: Mario Rothauer ***@***.***> 
Gesendet: Mittwoch, 1. März 2023 08:54
An: anstiftung/mapped-repair-events ***@***.***>
Cc: Ina Hemmelmann ***@***.***>; Author ***@***.***>
Betreff: Re: [anstiftung/mapped-repair-events] iCal Feed (Issue #115)

 

Und bitte auch, um welche Initiative / welchen Termin es sich gehandelt hat. Danke.

**Comment by mrothauer** [comment]
Danke fürs Nachfragen. Ich habs mir nochmal angeschaut und konnte leider keine Auffälligkeiten erkennen.
