### ISSUE TITLE
Laufzetteleingabe ergonomischer

### ISSUE THREAD

**Issue by w8970** [anstiftung/mapped-repair-events#120]
Bei der Eingabe eines neuen Laufzettels finde ich es schön, wenn man möglichst viel mit der Tastatur machen kann und Mausbewegungen und -klicks nur minimal nötig sind.

https://www.reparatur-initiativen.de/laufzettel/add/<laufzettel_id>

Bei der Eingabe von "Kategorie" und "Marke" wäre es schön, wenn der Cursor gleich in die Eingabezeile ("Suchbegriff eingeben") gesetzt werden würde und man ohne in das Eingabefeld klicken zu müssen, gleich losschreiben kann.

Ist es möglich, das zu verbessern?

VG,
Erik vom RepairCafé Dresden und Freital

**Comment by w8970** [comment]
Seems to be fixed in the latest version, thank you! :-)

**Comment by mrothauer** [comment]
@w8970 ist ist mir das am allerliebsten :)
