### ISSUE TITLE
Verbesserung Übersicht "Meine Termine"

### ISSUE THREAD

**Issue by w8970** [anstiftung/mapped-repair-events#121]
Ich bin in mehreren RepairCafés aktiv und habe also mehrere Initiativen auf der Seite: https://www.reparatur-initiativen.de/meine-termine

Mich stört, dass beim Aufruf der Seite immer die erste Initiative aufklappt. Ich bin dort zwar aktiv, aber die Laufzettel verwaltet jemand anders. Ich verwalte die Laufzettel der 2. und 3. Initiative in der Liste. Ich muss also immer die erste Initiative zuklappen (weil da sehr viele Termine eingetragen sind) und dann die zweite oder dritte aufklappen.

Es wäre für mich eine Verbesserung wenn:
a) sich für den Nutzer gemerkt würde, welche Initiative er zuletzt aufgeklappt hatte und diese wieder aufgeklappt würde oder
b) die erste Initiative nicht aufklappt, wenn man in mehreren Initiativen aktiv ist.

Wäre das möglich?

VG,
Erik vom RepairCafé Dresden und Freital

**Comment by mrothauer** [comment]
Hallo @w8970 
hat ein wenig gedauert, ich hoffe, es passt so.
Ich habe mich für die einfacher umzusetzende Variante b entschieden.
Schöne Grüße,
Mario

**Comment by w8970** [comment]
Hallo @mrothauer vielem Dank, klappt gut. :+1: 
VG, Erik

**Comment by mrothauer** [comment]
@w8970 sehr schön, danke fürs feedback!
