### ISSUE TITLE
Schriftfarbe der Highlight 

### ISSUE THREAD

**Issue by eaCe** [anstiftung/mapped-repair-events#133]
Hallo, erst einmal vielen Dank für das tolle Projekt!
Die Highlights finde ich schwer lesbar. Wäre es an der Stelle nicht besser, die Schriftfarbe auf weiß zu setzen?

https://github.com/anstiftung/mapped-repair-events/blob/0430713f319049d1c2ef699caa778189d426432c/webroot/css/frontend.css#L1381C18-L1381C18

![grafik](https://github.com/anstiftung/mapped-repair-events/assets/2708231/6194deb9-d4ac-4784-a703-1b1bdfbcff6f)

**Comment by mrothauer** [comment]
Hi,
ich finde auch, dass weiß da besser wäre.
Was meinst du, @inahmmlmnn ?
<img width="874" alt="image" src="https://github.com/anstiftung/mapped-repair-events/assets/527787/f378b50f-5895-49bc-8840-c9cc0a8de1af">

**Comment by inahmmlmnn** [comment]
Ja, gefällt mir und ist auch besser lesbar. Gerne ändern!
Bedeutet ja nichts für die normalen Linkfarben ohne farbige Hinterlegung, nehme ich an?

Lg
Ina

 

Von: Mario Rothauer ***@***.***> 
Gesendet: Mittwoch, 13. Dezember 2023 13:33
An: anstiftung/mapped-repair-events ***@***.***>
Cc: Ina Hemmelmann ***@***.***>; Mention ***@***.***>
Betreff: Re: [anstiftung/mapped-repair-events] Schriftfarbe der Highlight (Issue #133)

 

Hi,
ich finde auch, dass weiß da besser wäre.
Was meinst du, @inahmmlmnn <https://github.com/inahmmlmnn>  ?
image.png (view on web) <https://github.com/anstiftung/mapped-repair-events/assets/527787/f378b50f-5895-49bc-8840-c9cc0a8de1af>

**Comment by mrothauer** [comment]
@inahmmlmnn genau, das wäre dann nur für die highlight-einträge auf der widget-seite
ich mach das dann mal, geht beim nächsten deploy mit online.

**Comment by inahmmlmnn** [comment]
Merci!

 

Von: Mario Rothauer ***@***.***> 
Gesendet: Mittwoch, 13. Dezember 2023 14:55
An: anstiftung/mapped-repair-events ***@***.***>
Cc: Ina Hemmelmann ***@***.***>; Mention ***@***.***>
Betreff: Re: [anstiftung/mapped-repair-events] Schriftfarbe der Highlight (Issue #133)

 

@inahmmlmnn <https://github.com/inahmmlmnn>  genau, das wäre dann nur für die highlight-einträge auf der widget-seite
ich mach das dann mal, geht beim nächsten deploy mit online.

**Comment by mrothauer** [comment]
Danke @eaCe fürs den Input!

**Comment by eaCe** [comment]
Danke euch :)
