### ISSUE TITLE
Terminabonnement auf Initiativenprofilseite präsenter hervorheben

### ISSUE THREAD

**Issue by mrothauer** [anstiftung/mapped-repair-events#142]
* [x] Toggle-Button, Breite von Kalender, "Termine abonnieren"
* [x] (149 Termine, 178 Laufzettel, XY Termin-Abonnements) - nur die bestätigten anzeigen?
* [x] Anzahl der Termin-Abos ist auch im Adminbereich zu finden
* [x] Email-Text der Benachrichtigung (1 Woche vor Termin) abändern und als HTML darstellen + Datum + Uhrzeit mit rein
* [x] Termin-Abo-Bestätigungs-Mail auch in HTML
* [x] SignatureEmailHtml als Override für Demokratiecafe
* [x] Wenn Initiative geändert wird: Geänderte Felder in E-Mail mit rein "z.B. Uhrzeit alt: xx-xx, Uhrzeit neu: xx-xx", E-Mail als Html

**Comment by LinnQu** [comment]
Hej Mario,
was hältst du davon, um die Möglichkeit des Terminabos auf der jeweiligen Initiativenseite stärker hervorzuheben, fügen wir einen Button ein, der sich ausklappen lässt. Dabei orientieren wir uns an der Funktion/Farbigkeit/Gestaltung an den Buttons für die Widgets (https://www.reparatur-initiativen.de/widgets/integration). Vorschlag: Der Button geht über die gesamte Breite des Kalenders in der Desktopansicht. Auf der mobilen Seite über die Breite der Terminansicht. Auf dem Button steht: "Termine abonnieren" alternativ "Termine dieser Initiativen abonnieren". Wenn man den Button ausklappt, erscheitt der Texte wie er jetzt schon auf der Seite steht. Wir könnten dann noch überlegen, ob wir den Button direkt unter den Kalender nehmen und die Möglichkeit, die Termine mit dem eigenen digitalen Kalender zu synchronisieren darunter. 

Es wäre ja dann so, dass diese Änderung auch bei den Demokratiecafés live gehen würde, daher müssen wir darauf achten, dass die Formulierungen für beide Seite stimmig sind. Ist das so?

Zudem möchten wir ja gern den Initiativen anzeigen, wie viele Personen ihre Termine abonniert haben. Mein Vorschlag wäre, dass wir dies unter >Meine Funktionen > Meine Termine (https://www.reparatur-initiativen.de/meine-termine) anzeigen und zwar hinter der Anzeige der Laufzettel. Bsp.: Reparaturcafé XY (149 Termine, 178 Laufzettel, XY Termin-Abonnements)

LG Linn

**Comment by mrothauer** [comment]
![image](https://github.com/anstiftung/mapped-repair-events/assets/527787/4e5fd3fe-38d4-4c25-a55d-7447e66533cd)

**Comment by mrothauer** [comment]
![image](https://github.com/anstiftung/mapped-repair-events/assets/527787/54fe67d8-d97e-425f-a207-14ba816003fc)

**Comment by mrothauer** [comment]
Jetzt kannst du das auf [test](https://test.reparatur-initiativen.de/) testen.
Ich habe alle Abos gelöscht. Du kannst gerne neue Test-Abos hinzufügen, musst mir aber Bescheid sagen, da das tägliche automatische Versenden der Info-Mails um 8 Uhr auf dem Test-Server nicht ausgeführt wird. Das muss ich manuell machen. Das ist aber nicht unbedingt notwendig, da du eh den Screenshot hast.

**Comment by LinnQu** [comment]
Hej Mario, schaut gut aus. Ich finde, der Kasten passt super über den Kalender. In der mobilen Version "hängt" der Kasten jedoch direkt an den Reparaturbereichen. Könntest du die beiden Kästen voneinander absetzen? Mein Testen war soweit erfolgreich. Ja, bitte auch noch die E-Mail anpassen, die versendet wird, wenn sich etwas geändert hat. Gern so wie von dir beschrieben. Und es gibt noch eine vierte E-Mail, die wird versandt, wenn ein Termin gelöscht wird. Leite ich dir weiter. Diese bitte auch noch entsprechend dem neuen Design anpassen. Liebe Grüße, Linn

**Comment by mrothauer** [comment]
Hi Linn,
* [x] mobiles Layout ist gefixt
* [x] E-Mail bei Terminänderung umgesetzt

Bitte noch ein letztes Mal testen auf test, dann stelle ich alles live.

Hier eine Mail in dem alle von mir umgesetzten Event-Änderungen gemacht wurden:
![image](https://github.com/anstiftung/mapped-repair-events/assets/527787/447d42ba-ab9c-4eea-9a73-6d4f32440818)

* Die Ort-Änderung wird immer dann angezeigt, wenn sich lat oder lng ändern (also der Ort wirklich physisch ein anderer ist).
* Denkbar wäre noch eine Zeile "Der Termin ist jetzt ein Online-Termin bzw. Der Termin ist kein Online-Termin mehr) - keine Ahnung wie oft das vorkommt, dass das geändert wird.
* Ich hab mich auch dagegen entschieden, die alte Uhrzeit bzw. das alte Datum anzuzeigen, da das versehentlich als das neue gelesen werden kann (wenn man die Mail nur überfliegt)

**Comment by mrothauer** [comment]
Hab jetzt noch die Änderung "is_online_event" in die Mail mit reingepackt und das Problem mit dem Löschen beseitigt.
Es kann ein letztes Mal getestet werden!

**Comment by mrothauer** [comment]
Hab die Änderungen noch angepasst und die Änderungen jetzt gerade online gestellt.

> Und der ausgeklappte Kasten steht auf der rechten Seite ca. 1 Pixel über dem Rand. (siehe Screenshot)

Welcher Browser? Firefox?

> Nur zur Info: Was mir grundsätzlich noch aufgefallen war. Ich hatte mir zum Testen zwei neue Initiativen angelegt. Wenn ich dort das erste Mal auf "Daten absenden" gedrückt habe, wurde ich jeweils auf die Startseite unserer Webseite weitergeleitet, ohne dass ein Abonnement abgeschlossen wurde. Beim zweiten Klicken hat es dann funktioniert. Bei den Initiativen die schon da waren, hat es ohne Probleme sofort funktioniert. Vielleicht kannst du mit der Info etwas anfangen.

Da steckte ein Spamschutz dahinter. Da die Box jetzt weiter oben zu finden ist,  hab ich das Limit auf 1 Sekunde (vorher 3) runtergeschraubt. Sollte alles funktionieren.

**Comment by LinnQu** [comment]
Hej!
Bei mir schaute das sowohl in Firefox auf dem Laptop wie auch mit dem Ecosia Browser auf dem Smartphone so aus, dass der Kasten rechts leicht überhängt.
LG Linn

**Comment by mrothauer** [comment]
> Hej! Bei mir schaute das sowohl in Firefox auf dem Laptop wie auch mit dem Ecosia Browser auf dem Smartphone so aus, dass der Kasten rechts leicht überhängt. LG Linn

danke - ist jetzt gefixt `padding: 0.5%` haben die Browser unterschiedlich gerendert...
