### ISSUE TITLE
E-Mails schöner und verständlicher gestalten

### ISSUE THREAD

**Issue by mrothauer** [anstiftung/mapped-repair-events#145]
* [x] E-Mails als HTML verschicken
* [x] Texte ändern

TODO
* [x] new_password_request.php
* [x] registration_successful.php
* [x] user_delete_request.php
* [x] workshop_added_or_changed.php
* [x] workshop_application_approved.php
* [x] workshop_application.php

DONE
* [x] activate_worknews.php
* [x] debug.php
* [x] event_changed.php
* [x] event_deleted.php
* [x] event_next_week.php

**Comment by mrothauer** [comment]
Hallo @inahmmlmnn,
ich hab die im oberen TODO-Block vermerkten E-Mails soeben auf HTML umgebaut und online gestellt.
Es sollte alles passen, aber vielleicht fällt dir ja noch was auf.
Lg,
Mario

**Comment by inahmmlmnn** [comment]
Alles klar, soll ich was testen oder einfach im Kopf behalten, falls wo was ruckelt?

Danke
Ina

 

Von: Mario Rothauer ***@***.***> 
Gesendet: Donnerstag, 16. Mai 2024 10:27
An: anstiftung/mapped-repair-events ***@***.***>
Cc: Ina Hemmelmann ***@***.***>; Mention ***@***.***>
Betreff: Re: [anstiftung/mapped-repair-events] E-Mails schöner und verständlicher gestalten (Issue #145)

 

Hallo @inahmmlmnn <https://github.com/inahmmlmnn> ,
ich hab die im oberen TODO-Block vermerkten E-Mails soeben auf HTML umgebaut und online gestellt.
Es sollte alles passen, aber vielleicht fällt dir ja noch was auf.
Lg,
Mario

**Comment by mrothauer** [comment]
@inahmmlmnn Es reicht, wenn du das im Kopf behältst, dass da was geändert wurde.
Danke,
Mario
