### ISSUE TITLE
Registrierung verbessern

### ISSUE THREAD

**Issue by mrothauer** [anstiftung/mapped-repair-events#162]
* Passwort nicht in der E-Mail mit dem Aktivierungs-Link senden
* Passwort erst nach erfolgter Aktivierung in Extra-Mail zusenden

**Comment by mrothauer** [comment]
@inahmmlmnn 
Hab das jetzt erledigt, gut getestet und und live gestellt.
Lg,
Mario

**Comment by inahmmlmnn** [comment]
Danke, Mario!
Ich habe gestern Abend 8.10., 19:33 eine Rückmeldung per Mail gehabt, dass die Aktivierung nicht ging – warst du da gerade am Umstellen? Sonst beobachte ich mal, was der User mir noch zurückmeldet und gebe dir ggf. Bescheid.

Lg
Ina

 

Von: Mario Rothauer ***@***.***> 
Gesendet: Mittwoch, 9. Oktober 2024 11:08
An: anstiftung/mapped-repair-events ***@***.***>
Cc: Ina Hemmelmann ***@***.***>; Mention ***@***.***>
Betreff: Re: [anstiftung/mapped-repair-events] Registrierung verbessern (Issue #162)

 

@inahmmlmnn <https://github.com/inahmmlmnn> 
Hab das jetzt erledigt, gut getestet und und live gestellt.
Lg,
Mario

**Comment by mrothauer** [comment]
@inahmmlmnn nein gestern hab ich nur was auf test gestellt
