### ISSUE TITLE
Bei vergangenen Terminen wird "Termin bearbeiten" angezeigt

### ISSUE THREAD

**Issue by mrothauer** [anstiftung/mapped-repair-events#23]
Und wenn man drauf klickt, kommt die Fehler-Seite "Sorry, Seite nicht gefunden".

Lösungsvorschlag:
"Termin bearbeiten" gar nicht anzeigen (duplizieren auch nicht)?
"Termin löschen"?

Oder: Termin in Kalender gar nicht anzeigen?

Beispiel (Link funktioniert nur im Februar 2020):
https://www.reparatur-initiativen.de/dbs

![image](https://user-images.githubusercontent.com/527787/74320670-55926980-4d81-11ea-8bc7-6d26a3d4b66c.png)

**Comment by inahmmlmnn** [comment]
Das ist ja immer nur der aktuelle Monat, in dem die vergangen Termine angezeigt werden - und das hatten wir so eingestellt, damit auf der Home der Monatskalender zum Monatsende nicht leer wird.

Ist es denn möglich, nur bei den vergangenen Terminen die Buttons wegzunehmen, wenn man den Terminpunkt anklickt? Dann würde ich das machen. Und dann muss "löschen" auch nicht angezeigt werden, weil der Termin dann ja sowieso schon passé ist.

**Comment by mrothauer** [comment]
Alles klar. "Termin duplizieren" dann auch nicht anzeigen, oder? Also gar keinen Button bei vergangenen Terminen.

**Comment by inahmmlmnn** [comment]
Ja, genau.
