### ISSUE TITLE
fullcalendar.io update to v5

### ISSUE THREAD

**Issue by mrothauer** [anstiftung/mapped-repair-events#35]
https://fullcalendar.io/docs/upgrading-from-v4
also update all other npm vendors

**Comment by inahmmlmnn** [comment]
Einfach updaten passt, ich hab bei den Demos nichts entdeckt, was sinnvoll für unseren Zweck wäre. Danke!

**Comment by inahmmlmnn** [comment]
Darstellung: In Firefox sind in den grau hinterlegten/"vergangenen" (inkl. Datum heute) Terminen die Trennlinien zwischen den Tagen nicht zu sehen.
In IE sind die Linien sichtbar, aber hier liegt über dem rechten Kalenderrand eine Scrollbar über den Feldern (die nicht notwendig/scrollbar ist).

Nur FF: Wenn ich auf der Home im Kalender einen Termin anwähle und sich darunter die Box mit der Terminliste öffnet, ist die Punktetrennlinie über dieser Liste dicker als über dem Such-Kasten-Feld rechts davon.

**Comment by mrothauer** [comment]
danke fürs ausführliche testen! alles gefixt und gleich live.

**Comment by inahmmlmnn** [comment]
Danke! Eine Kleinigkeit ist mir noch aufgefallen: Die Mouseover-Farbe bei den Kalenderpfeilen ist eine andere als bei den Suchbuttons. Ästhetisches Detail, aber vielleicht kannst dus noch anpassen? :-)

**Comment by inahmmlmnn** [comment]
Und eben hier noch entdeckt: https://www.reparatur-initiativen.de/repair-cafe-im-habitat
In Firefox sind zwei Begrenzungslinien um den Tag, and em der Termin eingetragen ist, nicht sichtbar.

**Comment by inahmmlmnn** [comment]
Und eben hier noch entdeckt: https://www.reparatur-initiativen.de/repair-cafe-im-habitat
In Firefox sind zwei Begrenzungslinien um den Tag, and em der Termin eingetragen ist, nicht sichtbar.

**Comment by mrothauer** [comment]
alles gefixt. lg
