### ISSUE TITLE
You have chosen the wrong licence for the project, please fix it quickly

### ISSUE THREAD

**Issue by mvqzcbrp** [anstiftung/mapped-repair-events#4]
Please fix quickly the license before the first contributions from other people get into the project. You have made the error to choose the GPLv3 license instead of the AGPLv3 license. The copyleft and all other benefits from the great GPLv3 license does not apply to your website-code because its a website and thus a SAAS (software as a service).
https://en.wikipedia.org/wiki/Software_as_a_service
https://en.wikipedia.org/wiki/GNU_Affero_General_Public_License

I like fixing things at my place listed in www.reparatur-initiativen.de . Thus i also happily like to fix this licensing issue :)

**Comment by inahmmlmnn** [comment]
Hi! We contacted our lawyer again and showed him your suggestion. Our conclusion is to keep the licence as it is.
(The AGPL-3.0 is the sister license of the GPL-3.0, which is only distinguished by the fact that in a pure SaaS, the user can use the source code of modified versions. With the GPL-3.0 the Copyleft, on the other hand, is only neccessary if copies of the software were passed on or offered by download. The AGPL-3.0 is just as compatible with the tested licenses as the GPL-3.0, but the GPL-3.0 does not allow relicensing under the AGPL-3.0. This means that the pre-existing components under the GPL-3.0 also must remain under the GPL-3.0, but may be used together with AGPL-3.0 components.)
