### ISSUE TITLE
Widget Einbindung

### ISSUE THREAD

**Issue by inahmmlmnn** [anstiftung/mapped-repair-events#6]
Hej Mario,

folgendes Terminwidget sollte eingebunden werden: 
<iframe width="350" height="140" style="border:3px solid #000; background:#FFC;" src="https://www.reparatur-initiativen.de/widgets/events?id=1234&num=2&trunc=330px"></iframe> 
Die Darstellung war nicht korrekt/nicht responsive.

Ich habe gerade versucht, das nachzuvollziehen und konnte keinen Widgetcode (sowohl Termin- als auch Kartenbox) in einen Blogpost/eine Seite einbauen - der Editor hat das nach dem Speichern im Quellcode immer gelöscht?

**Comment by mrothauer** [comment]
sorry, da waren die filter zu restriktiv eingestellt. iframes sind nun für admins zugelassen, für alle anderen user nur youtube / vimeo videos.
see https://github.com/anstiftung/mapped-repair-events/commit/2d32df62edc51869817b7c9fd8c95a9a1e8d2edc
